### ISSUE TITLE
When (manually) caching embeddings this line breaks the order and renders caching useless

### ISSUE THREAD

**Issue by alexeifigueroa** [embeddings-benchmark/mteb#1366] opened 2024-10-30 17:23 UTC
https://github.com/embeddings-benchmark/mteb/blob/992d470eea34fc9c2cc684d40d6854e9567c7f72/mteb/evaluation/evaluators/PairClassificationEvaluator.py#L84

consider a change for
`sentences = list({s:None for s in self.sentences1 + self.sentences2}.keys())`

**Comment by isaac-chung** [comment] 2024-10-30 20:04
Hi! Would you mind sharing a minimally reproducible example and the outputs? Would really help us understand the context more. Thanks!

**Comment by isaac-chung** [comment] 2024-12-15 22:41
Closing this now. Cannot reproduce. Feel free to reopen with a reproducible example.

**Closed by isaac-chung** 2024-12-15 22:41 UTC
Labels: more-information-needed
