### ISSUE TITLE
Average scores on multilingual tasks?

### ISSUE THREAD

**Issue by turian** [embeddings-benchmark/mteb#117] opened 2023-06-14 12:44 UTC
The "Overall MTEB English leaderboard" has an averages column, which is very useful.

However, the leaderboards with many languages (Bitext Mining and Classification) have no average, and it's very difficult to assess with such large tables what the multilingual performance is.

Would it be possible to include a micro and macroaverage over the tasks? The macro-average would first average all tasks in a particular language, and then average over languages. The micro-average would average all tasks evenly.

**Comment by Muennighoff** [comment] 2023-06-14 13:11
Good point, have been thinking about how to improve that.

1. For the macro-average, the problem is that some languages only have very few tasks, so when you average over languages the averaging will be very distorted I think. Also it's ambiguous what language to attribute crosslingual datasets to.

2. For the micro-average IIURC you would first average all scores for each task (regardless of language) & then average the tasks. This seems reasonable & would give a multilingual average in some sense. However, most models only have English scores, which would limit the usefulness as we can't compute averages for many models that miss scores. To display it one could partition the `Overall` tab into a `English` & `Multilingual` tab. Also, need to think about whether or not to include the `German` clustering tab in that average 🧐

3. An alternative is to gradually develop Overall tabs for individual languages, however, currently, the limited number of languages that have multiple tasks make this not super useful I think. Only for German, it may be worth it, as there are `Classification`, `Clustering` & `STS` scores for it.

4. Another alternative is to add an `Average` & `Rank` column for each task in their respective tabs. This way one could inspect the `Bitext Mining` Average, `German Clustering` Average, `Multilingual STS` Average etc. This is the most complex one from a coding perspective, but my favorite solution (together w/ 3. as more multilingual datasets are added)

What do you think?

**Comment by turian** [comment] 2023-07-01 17:27
@Muennighoff yeah so I've been playing with this dataset a little too. I do think exposing some overall numbers is very important, because people want to make quick judgments of which baseline to start with, and only later refine the model choice as their evaluation methodology on their particular problem improves.

At the very least, having a grand score for Multilingual Classification and Multilingual Bitext Mining would be great.

There are two key issues as I see it:
1) Missing data
2) How to weight / average across tasks

BTW I'm using task to mean dataset here, not the task type (Classification / Bitext Mining).

## Missing data

I think this is the more important of the two questions.

For Classification leaderboard, 15 models and 117 tasks. 19% cells are NaN (missing).

For Bitext leaderboard, 65 models and 131 tasks. 64% of the cells are NaN (missing).

The general pattern for these leaderboards is that some models are evaluated on all the tasks. And some models are only evaluated on some tasks (but almost always the same tasks are skipped for these incomplete model rows).

The simplest solution would be that you could pick one reference model, and then all models that don't have scores for all the reference model's tasks would be grayed out and ignored. Similarly, all tasks not scored by the reference model would be grayed out.

Another approach would be to impute the missing values, and display them in a different color. I could explain this in more detail if you are interest.

## Task weighting

What's nice and makes your job easier is that for a particular task type, all scores are the same kind. This stuff is much more painful if you have like Classification tasks with AUC and some with f1 etc.

* I agree that the simplest idea would be micro-averaging by language or language pair. As you said, you average the scores first of all tasks with the same language. Then you average over all languages. That would be my vote.
* Agreed that macro-averaging and treating all tasks as having equal weight makes less sense. Unless you had prior knowledge that the more tasks a language/language-pair has, the more important people consider that language/language-pair. In which case, macro could be a nice alternative.
* Lastly, you might wish to consider an option to weight tasks based upon the popularity of the language. There are a handful of ways to do this that I could describe (including log-weighting), if this is of interest to you.

**Comment by Muennighoff** [comment] 2023-07-20 17:43
Have added average scores for each [task tab](https://huggingface.co/spaces/mteb/leaderboard)! Let me know if you think it should be done differently!

**Comment by KennethEnevoldsen** [comment] 2024-01-15 09:50
It would also be great to see a multilingual column tab for both overall and each category. I think a naive mean across languages (pr. task) and then across tasks is a great starting point. This def. leads to the overweighting of certain languages (e.g., the Scandinavian languages), but they are already close to English, and ranking (on multilingual models) generally seems to match quite well (comparing the Scandinavian Embedding Benchmark to MTEB), so it will likely have the expected effect of down-weighting English-only models.

**Comment by KennethEnevoldsen** [comment] 2024-01-15 10:14
Yeah, retrieval is definitely the hardest to find reasonable datasets for (at least if we avoid translations of existing datasets). I have at least one over at SEB (which hasn't been added to MTEB just yet - but that will come). However, we have a few collaborations with Danish Industry partners that might resolve in useable datasets.

There might also be other good sources that can be leveraged into new datasets that I am missing. We experimented a bit with creating a dataset using LLMs to generate questions for context and then re-retrieve the context.

**Comment by shivrajjadhav733** [comment] 2024-03-04 14:55
I see an overall problem with numbers on leaderboard.
I am trying few models on Retrieval task type with SciFact dataset for English Language. 


`

from mteb import MTEB
from sentence_transformers import SentenceTransformer

# Define the sentence-transformers model name
model_name = "infrastructure/Stella-base-en-v2"

model = SentenceTransformer(model_name)
evaluation = MTEB(tasks=["SciFact-PL"], task_langs=[“en”])
results = evaluation.run(model, output_folder=f"results/{model_name}")

`

The results json output file has ndcg_at_10 showing values like 0.35 or 0.36


I tried variety of different models and the numbers listed on leaderboard are about 72 or 74 etc. 

So there is huge difference in the number got thru running script.


I have tried it on MacOS(M1 chip) as well as AWS EC2 g5 instance (Ubuntu 22).
The results are almost similar but they are way off when compared to leaderboard.

is there a specific way to read the results.json against leaderboard numbers?

**Comment by KennethEnevoldsen** [comment] 2024-06-05 18:42
We are currently working on this in the latest release and have some ongoing discussions in #839. Will close this issue here to avoid duplicated

Related to #752, #839

**Closed** 2024-08-15 08:19 UTC
Labels: enhancement
