### ISSUE TITLE
Leaderboard: Add query parameters to link

### ISSUE THREAD

**Issue by x-tabdeveloping** [embeddings-benchmark/mteb#1440] opened 2024-11-12 07:53 UTC
Similar to the old leaderboard we could get some query parameters from the URL thereby making specific benchmarks' leaderboards shareable.
Unfortunately gradio does not currently allow manipulation of the URL programmatically. I see two ways out of this:
1. We file an issue, and request that they implement it.
2. We add a `share` button that templates the link with the appropriate query parameters and copies it to the clipboard. This will, however result in a discrepancy between the link people copy from the header vs that link they get from this button.

**Comment by isaac-chung** [comment] 2024-12-18 21:15
Duplicate of https://github.com/embeddings-benchmark/mteb/issues/1518

**Closed by isaac-chung** 2024-12-18 21:15 UTC
Labels: leaderboard
