### ISSUE TITLE
Refresh after submitting model issues

### ISSUE THREAD

**Issue by raghavlite** [embeddings-benchmark/mteb#774] opened 2024-05-20 21:52 UTC
I uploaded my model here. Added the mteb_metadata.md to the top of readme.md

Here is my model: https://huggingface.co/raghavlight/SE_v1/

I don't see the model on leaderboard after I hit refresh. Am I doing something wrong here?

Here is what I see after I hit refresh.
<img width="1493" alt="Screen Shot 2024-05-20 at 5 52 01 PM" src="https://github.com/embeddings-benchmark/mteb/assets/6205665/db9314e9-5cb8-4e41-8f65-6a32b934eec5">

**Comment by KennethEnevoldsen** [comment] 2024-05-21 08:15
@Muennighoff do you have time to have a look at what is going wrong here?

**Comment by Muennighoff** [comment] 2024-05-21 19:00
It looks like the Refresh button is broken. It completely changes the ranking and the composition of the Average (56 -> 27). I'm not sure what is happening but maybe @tomaarsen knows? I think we were discussing the Refresh button at some point 🤔

**Comment by KennethEnevoldsen** [comment] 2024-05-31 13:33
@Muennighoff or @tomaarsen this problem seems to be preventing people from submitting to the leaderboard (#857) - what is the best approach to take a look at that?

**Comment by tomaarsen** [comment] 2024-06-04 07:03
@Muennighoff We were indeed discussing the refresh button a while ago (back then the issue was that it caused everyone's leaderboard to display error messages in the top right), but I haven't made any changes to it. I suspect that the caching update perhaps broke it.
That said, models can still be submitted, correct? It's just hard/impossible to verify whether they actually work until an admin restarts the leaderboard?

- Tom Aarsen

**Comment by Muennighoff** [comment] 2024-06-05 03:17
> That said, models can still be submitted, correct? It's just hard/impossible to verify whether they actually work until an admin restarts the leaderboard?

Yes exactly!

**Comment by tomaarsen** [comment] 2024-06-05 09:05
I was able to dedicate a bit of time this morning and was able to fix it: https://huggingface.co/spaces/mteb/leaderboard/discussions/122
It was caused by a common but very devious bug.

- Tom Aarsen

**Comment by KennethEnevoldsen** [comment] 2024-06-05 10:11
Wonderful @tomaarsen - @raghavlite I assume this resolved the issue?

**Comment by KennethEnevoldsen** [comment] 2024-06-05 17:57
As it is merged, I will close this issue but feel free to re-open it if issues arise.

**Closed by KennethEnevoldsen** 2024-06-05 17:57 UTC
Labels: bug, leaderboard
