### ISSUE TITLE
Add zero-shot box to leaderboard

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#1404] opened 2024-11-07 15:36 UTC
Add a zero-shot box to the leaderboard. This also required adding annotations to models on whether they are zero-shot or not.

This also requires adding a default to benchmark whether zero-shot should be the default.

**Comment by x-tabdeveloping** [comment] 2024-11-12 07:32
This is a duplicate of #1372 I'm closing it

**Closed by x-tabdeveloping** 2024-11-12 07:32 UTC
Labels: leaderboard
