### ISSUE TITLE
FollowIR instruction format

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#1083] opened 2024-07-13 17:31 UTC
Why do we put the instruction after the query:
https://github.com/embeddings-benchmark/mteb/blob/db45092f31a1be05f264a0752fa68964a35b5927/mteb/evaluation/evaluators/RetrievalEvaluator.py#L357C22-L357C27

Wouldn't models like GritLM expect it to be `<|user|>\n{instruction}\n<|embed|>\n{query}`? Did someone try also using this format?

cc @orionw

**Comment by orionw** [comment] 2024-07-13 20:50
> Why do we put the instruction after the query:

Yeah this is actually decently complicated. The short answer is, it depends on the model which is best.

- Note this is not the `prompt` which is what GritLM uses, this is the instance-level instruction. It is possible to take both and have a prefix, query, and instruction
- This is just the default for the `instruction` for models that are wrapped with `DRESModel` and don't have an `encode_queries` function (so basic SentenceTransformer models).  At least in my implementation of GritLM which I took from your repo it never called this code since it has a custom `encode_queries` function. I haven't looked at how we've created the model implementations in `mteb` but I would be surprised if it didn't do the same.
- For my experiments I tried several combinations for each model. IIRC for LLM2Vec as an example, it was best to use it after and use a generic prompt prefix ("Answer the question" + query + instruction). For GritLM I just used your formatting template (see [code here](https://github.com/orionw/FollowIR/blob/master/models/gritlm/downloaded_gritlm.py#L87)) in place of the prefix.  It actually varied a lot depending on the model so I just chose the best performing one.

If you think we should change the default in the code happy to switch. But this code is generally for models which don't take instructions and in my experience they work a little better with the instruction after (again, note that the `instruction` is not the `prompt`).

All of this is another good reason why we should be logging the instruction/prompt if we can to the results as there are large number of potential ways people can do them.

**Comment by Muennighoff** [comment] 2024-07-13 21:09
Thanks for the detailed response! One problem may be that if people now evaluate GritLM via `mteb.get_model(...)` then it would not reproduce your scores afaict? 🤔 But maybe this is fine for now and people should just use a custom model not `mteb.get_model` in that case.

**Comment by orionw** [comment] 2024-07-13 23:48
atm I think all of them don't reproduce unless you use the code in the FollowIR repo. All of them have to be modified to handle the case where there is a query, prompt, AND a query-specific instruction.

I hope to take a closer look at this in the coming weeks along with getting #905 merged in.  I think that will help make it more standard/generalizable to new query-specific instruction tasks as well.

**Comment by KennethEnevoldsen** [comment] 2024-09-09 15:45
I believe we can close this PR -  @orionw is that the case?

**Comment by orionw** [comment] 2024-09-09 15:51
Yes, I’ll close this. 

I’m releasing a new paper+model in a week that I think will merit some more discussion/changes around these lines but will save it for then 👀

**Closed by orionw** 2024-09-09 15:51 UTC
