### ISSUE TITLE
Killed process in running scripts/run_mteb_english.py

### ISSUE THREAD

**Issue by bm777** [embeddings-benchmark/mteb#125] opened 2023-07-25 11:37 UTC
I'm trying to evaluate a model I have fine-tuned using knowledge distillation. It took me 14 days in a Single GPU Tesla V100.

I faced this error of being killed after trying o run the benchmark on the 62 datasets on all tasks using `python scripts/run_mteb_english.py,` I was expecting a 'Done' message, but I got this.

<img width="1440" alt="Screenshot 2023-07-25 at 13 05 33" src="https://github.com/embeddings-benchmark/mteb/assets/29865600/e8eb562d-c424-46aa-9640-9001909a4f4c">

This is the **Reranking** task, especially `MindSmallReranking` 

I'm suspecting the batch size of the data loaded for the GPU.

Would anyone know how to solve this without putting in comment that special task?

**Comment by Muennighoff** [comment] 2023-07-25 12:18
I think you're running out of CPU RAM as the embeddings are transferred to the CPU.
You could either

1) Get more CPU memory

2) Decrease the batch size (not sure this will help, but worth trying):
`evaluation.run(model, output_folder=f"results/{model_name}", eval_splits=eval_splits, batch_size=32)`

3) Cache embeddings (e.g. doing sth like [here](https://github.com/embeddings-benchmark/mtebscripts/blob/ddb21b4e147d7abf6e37202493c1696bd75671fe/run_array_openaiv2.py#L145))

**Comment by bm777** [comment] 2023-07-27 07:33
The problem persists, on the same task.
It is killed exactly at the same position.

<img width="539" alt="Screenshot 2023-07-27 at 09 30 48" src="https://github.com/embeddings-benchmark/mteb/assets/29865600/2506c207-ecd1-43f9-8a8b-66f44c570bf2">

**Comment by Muennighoff** [comment] 2023-07-27 07:38
Yeah I think you need to go with one of the other solutions, ideally getting more CPU RAM.

It will not have a score for `MindSmallReranking`, but you will have scores for all other datasets. There's also rankings in the individual task tabs now, so your model will still be ranked there 👍

**Comment by bm777** [comment] 2023-07-27 07:56
For the moment, I will skip it.

Thanks for your reply, I will show you the final ranking, if we get a good and reasonable score haha.

**Comment by bm777** [comment] 2023-07-31 09:46
I got some good results on some tasks. My model is above many embedding model results values, but because of the lack of CPU, the overall rank in the leaderboard put my model very behind.

The specific tasks, I really need to evaluate are retrieval and reranking, and summarization.

See the current result I have.

Embedding Dimensions : **768** 
Sequence Length : **514**
Average (56 datasets) : n/a
Classification Average (12 datasets) : **66.95**
Clustering Average (11 datasets) : **40.84**
Pair Classification Average (3 datasets) : **81.03**
Reranking Average (4 datasets) : n/a
Retrieval Average (15 datasets) : n/a
STS Average (10 datasets) : **80.17**
Summarization Average (1 dataset) : **32.39**

n/a, represent where I got the killed process, lack of CPU.

It remains a last chance, to use the Cache embeddings.
It looks promising, this model. 
![Screenshot 2023-07-31 at 11 20 08](https://github.com/embeddings-benchmark/mteb/assets/29865600/3c2e697d-bf3c-488f-8818-ae724d82f86a)

**Comment by Muennighoff** [comment] 2023-07-31 11:35
> I got some good results on some tasks. My model is above many embedding model results values, but because of the lack of CPU, the overall rank in the leaderboard put my model very behind.
> 
> The specific tasks, I really need to evaluate are retrieval and reranking, and summarization.
> 
> See the current result I have.
> 
> Embedding Dimensions : **768** Sequence Length : **514** Average (56 datasets) : n/a Classification Average (12 datasets) : **66.95** Clustering Average (11 datasets) : **40.84** Pair Classification Average (3 datasets) : **81.03** Reranking Average (4 datasets) : n/a Retrieval Average (15 datasets) : n/a STS Average (10 datasets) : **80.17** Summarization Average (1 dataset) : **32.39**
> 
> n/a, represent where I got the killed process, lack of CPU.
> 
> It remains a last chance, to use the Cache embeddings. It looks promising, this model. ![Screenshot 2023-07-31 at 11 20 08](https://user-images.githubusercontent.com/29865600/257182343-3c2e697d-bf3c-488f-8818-ae724d82f86a.png)

Looks great nice job! What should definitely work is creating the embeddings for all chunks and cache them. The problem is that currently, it will hold them all for memory.

Holding them all in memory is only necessary for scoring. There may be a way around this but not sure how.
You could try getting a bigger CPU machine only for the scoring part which is comparatively quick.

I'm surprised you're running out of RAM with just 768 dimensions - I think even Colab CPUs may have enough RAM for that.

**Comment by bm777** [comment] 2023-08-01 11:42
Which instance type do you recommend for this issue?

I can afford AWS EC2: Accelerated computing or Memory-optimized or compute-optimized?

![Screenshot 2023-08-01 at 13 41 39](https://github.com/embeddings-benchmark/mteb/assets/29865600/bca28650-0ee4-4057-9517-7ad7f8f87d9b)

**Comment by Muennighoff** [comment] 2023-08-01 12:23
> Which instance type do you recommend for this issue?
> 
> I can afford AWS EC2: Accelerated computing or Memory-optimized or compute-optimized? [Source](https://aws.amazon.com/ec2/instance-types/)
> 
> ![Screenshot 2023-08-01 at 13 41 39](https://user-images.githubusercontent.com/29865600/257503421-bca28650-0ee4-4057-9517-7ad7f8f87d9b.png)

I would try a colab notebook / kaggle notebook first. If that doesn't suffice then maybe memory-optimized.

**Comment by bm777** [comment] 2023-08-01 12:25
Colab was to slow. That is why I asked.
Will try memory-optimized.
-----
Thanks

**Comment by bm777** [comment] 2023-09-25 14:18
Hi @Muennighoff finally succeeded in running the benchmark. 

The refresh button on the leaderboard throws an Error.

Would someone restart the cache of the leaderboard?

**Comment by bm777** [comment] 2023-09-25 17:12
can I close the issue? @Muennighoff

**Comment by Muennighoff** [comment] 2023-09-25 17:41
Sure, here you go :)

**Closed by Muennighoff** 2023-09-25 17:41 UTC
